name: CI

on: [ push ]

env:
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
  FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Set up environment
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      # Prepare Flutter
      - name: Get dependencies
        run: flutter pub get
      - name: Generate Freezed models
        run: flutter pub run build_runner build --delete-conflicting-outputs

      # Lint
      - name: Check formatting
        run: flutter format --set-exit-if-changed .
      - name: Analyze code
        run: flutter analyze .

  test:
    runs-on: ubuntu-latest
    steps:
      # Set up environment
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      # Prepare Flutter
      - name: Get dependencies
        run: flutter pub get
      - name: Generate Freezed models
        run: flutter pub run build_runner build --delete-conflicting-outputs

      # Test
      # Temporary disabled due to absence of tests.
      # - name: Run tests
      #   run: flutter test

  build:
    runs-on: ubuntu-latest
    steps:
      # Set up environment
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      # Prepare Flutter
      - name: Get dependencies
        run: flutter pub get
      - name: Generate Freezed models
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Provide Firebase config file
        run: echo $FIREBASE_CONFIG | base64 --decode > android/app/google-services.json

      # Build
      - name: Build APK
        run: flutter build apk --dart-define=SENTRY_DSN=${SENTRY_DSN}
